#!/usr/bin/env ruby
#
# tribble-control -- power, flash and monitor the devices plugged into an
# ExSYS 16-port managed USB hub.  See `tribble-control --man`.
#
require 'tribble-control'

begin
    TribbleControl::CLI.run
rescue => e
    warn "#{TribbleControl::CLI::PROGNAME}: #{e.message || 'unknown'}"
    warn e.backtrace if $DEBUG
    exit 1
end
