#!/usr/bin/env ruby
#
# tribble-control -- power, flash and monitor the boards plugged into a
# switchable USB hub.  See `tribble-control --man`.
#
require 'tribble-control'

begin
    TribbleControl::CLI.run
rescue => e
    warn "#{TribbleControl::CLI::PROGNAME}: #{e.message || 'unknown'}"
    warn e.backtrace if $DEBUG
    exit 1
end
