#!/usr/bin/env ruby
#
# tribe-control -- power, flash and monitor the devices plugged into an
# ExSYS 16-port managed USB hub.  See `tribe-control --man`.
#
require 'tribe-control'

begin
    TribeControl::CLI.run
rescue => e
    warn "#{TribeControl::CLI::PROGNAME}: #{e.message || 'unknown'}"
    warn e.backtrace if $DEBUG
    exit 1
end
